### ISSUE TITLE
Do bool parsing using yaml

### ISSUE THREAD

**Issue by keeganmccallum** [aio-libs/yarl#1173]
### Describe the solution you'd like

Bools should be supported, is silly to need a disclaimer in README. All cases mentioned in README are supported as bools by yaml, just do yaml parsing and have a flag to opt-out in case folks want strings

### Describe alternatives you've considered

parsing on my own, which is less ideal, and more importantly a footgun for folks using libs that depend on yarl and haven't seen this nuance

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by webknjaz** [comment]
I understand that some people may want the obvious conversions of `"a="` that is `a = False` and `"b=wujfjrbf"` that means `b = True`. But yarl does not have such context and the semantics will always be ambiguous since all the information about how things are interpreted only exist on the calling side. There is no way for us to know what each specific user wants to call a boolean.
YAML is a bad example and an unacceptable dependency. In the latter case, it may say yes, while in the former, it'll be Norway 🤷‍♂️

There is no sane way to resolve this in code. Really.

**Comment by keeganmccallum** [comment]
yaml's bool parsing semantics are well known and cover most common cases (you don't need to have yaml as a dependency, just need to support the same semantics for default bool parsing as them), having this behaviour as opt-out or opt-in may not be "air tight" , but it doesn't need to be, and is better than not handling at all. yarl doesn't need to have the context of every possible boolean someone may wanna use, but can provide sane defaults, especially when the alternative is to not handle a very common/expect type like a boolean at all

**Comment by webknjaz** [comment]
This would be a footgun and is out of the scope. There is no `bool` in WHATWG and RFC specs. For example, `<input type="checkbox" value="1">` is sent over as a string `"1"` but is actually a boolean `True` most of the time when it's selected. But when it's deselected, it's an empty string `""` or outright missing.

If you can point to an accepted spec that defines this, we can talk about implementing that. Otherwise, a sane default is not having a footgun in the first place, which is already well-implemented.
