### ISSUE TITLE
Replace _val with separate props for url parts

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/yarl#172]
The target is `URL.build` optimization.
The method is crucial for aiohttp web server, avoiding `SplitResult` construction can make the method faster.

`SplitResult` could be restored in every method that need the object.

N.B. Serialization format should support URL classes generated by older library version or the format should not be changed at all (the later looks easier).

**Comment by bdraco** [comment]
#1396 will get a step closer to this

In the future we may want to change the split functions to unpack the values into named variables in future. ie `self._scheme, self._netloc, self._path, self._query, self._fragment = val` or store everything in `self._cache` as the single source of truth; However that was too large of a redesign for this PR since it would also require changing all the tuple unpacking and pre cache in `__new__`.

One consideration about getting rid of the `_val` tuple is that `SplitResult` is exposed as an allowed incoming value in new we would have to have code to convert it. With `_val` being a normal tuple, `SplitResult` can be passed in and its still compatible.

It would be a lot nicer if we stored everything in `self._cache` though since it means the `encode_url` and `pre_encoded_url` calls would return a simple dict that was pre-populated, and it also means `propcache` would have more keys pre-populated.

**Comment by bdraco** [comment]
https://github.com/aio-libs/yarl/pull/1397 implemented spitting it up but all the new names make it a bit slower and less readable.

We could use named vars instead but that's going to be just as slow

I think we aren't going to get any more out of this so I'll close this issue

**Comment by bdraco** [comment]
Second attempt in #1397 looks like it will work without regressing performance in a meaningful way
