### ISSUE TITLE
Allow joining URL and pathlib.Path

### ISSUE THREAD

**Issue by ukch** [aio-libs/yarl#185]
Given the following `URL` and `Path` objects:
```python
>>> url = URL("http://whatever/foo")
>>> path = pathlib.Path("bar/baz")
```
I would expect them to be joinable using code such as:
```python
>>> url / path
URL('http://whatever/foo/bar/baz')
```
Instead, I receive this traceback:
```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
    url / path
  File "/path/to/lib/python3.6/site-packages/yarl/__init__.py", line 281, in __truediv__
    name = self._PATH_QUOTER(name)
  File "yarl/_quoting.pyx", line 226, in yarl._quoting._Quoter.__call__
TypeError: Argument should be str
```

**Comment by asvetlov** [comment]
How do you want to join **absolute** path?

**Comment by ukch** [comment]
Currently, attempting to join a path starting with a slash onto an URL raises `ValueError: Appending path starting from slash is forbidden`. I would say the same behaviour should occur with absolute `Path` objects.

**Comment by asvetlov** [comment]
Another question is: should symlinks be resolved?

Now I have a feeling that `url / str(path)` is simple and good enough. Why do we need to blow up the API?

**Comment by asvetlov** [comment]
I have a feeling that the request is out of the library scope.

**Comment by Bobronium** [comment]
I stumbled upon this issue while trying to answer this question: is `pathlib.Path` suitable for dealing with url path?

The immediate concern that I have is that on windows `str(pathlib.Path('foo') / 'bar')` would result in a 'foo\bar'.

So, answering my own question: you probably shouldn't use `pathlib.Path` as url path constructor. 

But you desperate to do otherwise, using `pathlib.PurePosixPath` should at least avoid problem with separator described above.
