### ISSUE TITLE
typing module not supported in python < 3.5

### ISSUE THREAD

**Issue by jzipfler** [aio-libs/yarl#205]
It is not possible to import/run **yarl** on Python 3.4, because it requires the `typing` module, which is only available from version 3.5.

Edit: Python 3.4 is available as classifier in `setup.py`, whereas *python_requires* is set to `>= 3.5.3`

**Comment by asvetlov** [comment]
As of yarl 1.2 the support for Python 3.4 was dropped.
I'll fix `setup.py`, thank you.

**Comment by dralley** [comment]
@asvetlov  Ubuntu 16.04 LTS still uses Python 3.5.1, which does not support the typing module.

Additionally, the Python 3.5 software collection for CentOS and RHEL is also 3.5.1 (which is why I'm here).

I've only tested with CentOS and not with Ubuntu, but it should be broken there too: https://packages.ubuntu.com/xenial/python3

Sidenote to avoid filing a new issue: the Python version badges in the README and on PyPI still list 3.4 support.

**Comment by asvetlov** [comment]
I've released yarl 1.2.6 with removed 3.4 badge.
If you are still using Python 3.5.1 you can install older yarl 1.1 version.
Or use `pyenv` / deadsnakes PPA for installing a newer python.
I'm sorry but support a new software on old OS is not always easy.
If you've decided to use old Ubuntu -- you are free to use old aiohttp/yarl versions as well.
