### ISSUE TITLE
Why not subclass URL?

### ISSUE THREAD

**Issue by bsolomon1124** [aio-libs/yarl#312]
`URL` throws a `TypeError` in `__init_subclass__()`.  Why is this?  What is the reasoning behind it and what would be the dangers of subclassing `URL` to override a few methods?

For those tempted to do something diabolical such as:

```python
>>> del URL.__init_subclass__
>>> class MyURL(URL):
...     pass
```

What dangers await them?

**Comment by asvetlov** [comment]
Why do you want to extend `yarl.URL`?
Do you want to change internal logic or provide a couple of URL helpers as methods?

**Comment by bsolomon1124** [comment]
> Why do you want to extend `yarl.URL`?  Do you want to change internal logic or provide a couple of URL helpers as methods?

Both of the above:

- Add some new instance methods
- Override existing ones

I know that I could use composition, but really prefer inheritance and was just wondering what obvious red flags are behind `__init_subclass__` always raising like it does.

**Comment by asvetlov** [comment]
URL internal representation can be changed for the sake of speed optimization. If we expose nothing -- nothing is broken.
Consider URL as *final* class in Java terminology (or *sealed* in C#).
If URL has bugs -- they should be fixed.
If you need some domain-specific functionality you always can create first-level functions that accept URL object and return whatever you need.
How often do you derive from `pathlib.Path`?

**Comment by bsolomon1124** [comment]
Okay, thanks for that explanation @asvetlov.

**Comment by selimb** [comment]
@asvetlov Personally, I want to derive from `yarl.URL` in order to integrate it with [pydantic](https://pydantic-docs.helpmanual.io/usage/types/#classes-with-__get_validators__).

> How often do you derive from pathlib.Path?
[pydantic does](https://github.com/samuelcolvin/pydantic/blob/master/pydantic/types.py#L473)

Ended up using the diabolical `del yarl.URL.__init_subclass__` above, subclassed `yarl.URL` (let's call it `my.URL`) and implemented the magic methods required by pydantic. I then use `my.URL` throughout my entire application. This makes me happy.

I can appreciate it's a peculiar use case though, and understand the desire to make `yarl.URL` *final*. I don't personally mind the `del` workaround.

I'm raising this here because one annoyance remains: I need to `typing.cast(my.URL, ...)` all over the place to satisfy the type checker, because all of `yarl.URL`'s methods that return a `yarl.URL` "hard-code" the return type annotation, e.g.:
```python
    def __truediv__(self, name: str) -> URL: ...
``` 
instead of
```python
    T = TypeVar("T")  # or TypeVar("T", "URL")?
    def __truediv__(self: T, name: str) -> T: ...
```
(See [pep484](https://www.python.org/dev/peps/pep-0484/#annotating-instance-and-class-methods))
I'd be happy to raise a new issue and/or submitting a PR, if you're interested.
