### ISSUE TITLE
'%ec' can't be encoded right 

### ISSUE THREAD

**Issue by andrei-liauchuk-oomnitza** [aio-libs/yarl#729]
### Describe the bug

URL: https://andrei.com/api/v3?filter=serial_number like `%ec%`
`%ec` symbols can't be encoded correctly

### To Reproduce

```python
>>> from yarl import URL
>>> URL('https://andrei.com/api/v3?filter=serial_number like %ec%')
URL('https://andrei.com/api/v3?filter=serial_number+like+%EC%25')
```

### Expected behavior

```python
>>> from yarl import URL
>>> URL('https://andrei.com/api/v3?filter=serial_number like %ec%')
URL('https://andrei.com/api/v3?filter=serial_number+like+%25ec%25')
```

### Logs/tracebacks

```python-traceback
-
```

### Python Version

```console
Python 3.6.9
```

### multidict Version

```console
Version: 4.7.6
```

### yarl Version

```console
Version: 1.7.2
```

### OS

Ubuntu 14.04.5 LTS

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by mjpieters** [comment]
This is not a bug. `URL()` can will only encode non-ASCII characters to percent-encoding.

Any ASCII characters in the string passed to `URL()` **must** be valid for that part of the URL. In all parts of a URL the sequence `%hh` (percent plus two hex digits) is a raw encoded sequence, encoding a single character. The two `hh` characters can be any hex digit, the numbers 0 through to 9 and the letters `A`, `B`, `C`, `D`, `E` or `F`, which can be uppercase or lowercase: `%ec` is the same as `%EC`.

`URL()` can't distinguish between correct use of `%hh` and incorrect use. If `URL()` would behave like you state in your *expected behaviour* section, **valid URLs would end up being broken**. E.g. the URL `http://example.com/path?%D0%BA%D0%BB%D1%8E%D1%87=%D0%B7%D0%BD%D0%B0%D1%87` is a valid encoded URL containing UTF-8 characters (Cyrillic):

```python
>>> URL("http://example.com/path?%D0%BA%D0%BB%D1%8E%D1%87=%D0%B7%D0%BD%D0%B0%D1%87")
URL('http://example.com/path?%D0%BA%D0%BB%D1%8E%D1%87=%D0%B7%D0%BD%D0%B0%D1%87')
>>> URL("http://example.com/path?%D0%BA%D0%BB%D1%8E%D1%87=%D0%B7%D0%BD%D0%B0%D1%87").human_repr()
'http://example.com/path?ключ=знач'
```

If instead each `%` character was replaced by `%25` such a URL would be mangled entirely. Note that the `encoding` parameter to `URL()` only has an effect when there are non-ASCII characters in the input string:

```python
>>> URL("http://example.com/path?ключ=знач")
URL('http://example.com/path?%D0%BA%D0%BB%D1%8E%D1%87=%D0%B7%D0%BD%D0%B0%D1%87')
```

because valid encoded URLs can only use ASCII characters.

There are no methods on `URL()` that will accept an ASCII-only query parameters with `%` characters, unfortunately. 

You can either manually encode the `%` characters first; note that the `human_repr()` output **doesn't decode these to `%` either**:

```python
>>> URL('https://andrei.com/api/v3?filter=serial_number+like+%25ec%25')
URL('https://andrei.com/api/v3?filter=serial_number+like+%25ec%25')
>>> URL('https://andrei.com/api/v3?filter=serial_number+like+%25ec%25').human_repr()
'https://andrei.com/api/v3?filter=serial_number like %25ec%25'
```

or use [`urllib.parse.quote()`](https://docs.python.org/3/library/urllib.parse.html#urllib.parse.quote) or [`urllib.parse.quote_plus()`](https://docs.python.org/3/library/urllib.parse.html#urllib.parse.quote_plus) to quote the string for you before passing it to `URL()` or `URL.build()` or `URL().with_query()`.
