### ISSUE TITLE
Ability to remove a query value while retaining others

### ISSUE THREAD

**Issue by apmorton** [aio-libs/yarl#774]
### Is your feature request related to a problem?

I have a situation where I would like to get a query parameter, do something with it, and then pass the URL onto a lower layer _without_ that single query param.

The current API is awkward for this.

### Describe the solution you'd like

It would be nice to be able to pass kwargs to `update_query` with `None` value and have that remove those specific query params.

```python
actual = URL('http://test.com/path?a=1&b=2').update_query(a=None)
expected = URL('http://test.com/path?b=2')
assert actual == expected
```

Today this throws a `TypeError`

### Describe alternatives you've considered

Today you can accomplish this, but its somewhat awkward:
```python
url = URL('http://test.com/path?a=1&b=2')
query = url.query.copy()
del query['a']
actual = url.with_query(query)
expected = URL('http://test.com/path?b=2')
assert actual == expected
```

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by webknjaz** [comment]
`None` seems ambiguous. It's semantics can be misinterpreted. JS would use `null` in it's place and that would be transmitted over the wire as a string, for example.
The `None`- check is correct.
I think you could just use an empty string and semantically it'd be the same as an unset value, usually.
But if you want to really exclude it, I'd recommend going for a separate method for deleting the param rather than setting it to a magical sentinel value which would mean "instead of updating, remove".

**Comment by apmorton** [comment]
Assigning an argument to none `None` seems logical and consistent to me given the existing behavior of passing `None` to `with_query` and `update_query`.

A separate method is fine too, but given `None` explicitly has no meaning now (by way of `TypeError`) it seemed a good fit.

A single method is definitely more convenient - imagine the use case of mutating and renaming an existing query parameter.

```python
url.update_query(old=None, new=func(url.query['old']))
```

vs

```python
url.update_query(new=func(url.query['old'])).remove_query('old')
```

Either is an improvement, but I think the first is more ergonomic.

**Comment by webknjaz** [comment]
> Assigning an argument to none `None` seems logical and consistent to me given the existing behavior of passing `None` to `with_query` and `update_query`.

I disagree: for `with_query()`, the value of `None` can have the semantics of "no query" as it works with complex mappings. When working with a value of a param, the value is a primitive. `None` is ambiguous in this case.

As for `update_query()`, I think allowing `None` was a design mistake in that context since it's advertised as a way to patch individual params and this magic sentinel just removes them all.
